### ISSUE TITLE
External URL error

### ISSUE THREAD

**Issue by pedroms** [zjuasmn/sketch-react#2]
I was trying to view a Sketch file by URL but it always returns this error:

![image](https://user-images.githubusercontent.com/2458631/28627628-43e7dffc-721a-11e7-812c-0d1494942676.png)

The Sketch file I was trying to use: https://gitlab.com/gitlab-org/gitlab-design/raw/a0e4c65f3f00db49e361eed72f211e80a56651ae/progress/pedro/ci/ce%2332420-new-project-templates/ce%2332420-new-project-templates.sketch

Am I doing something wrong?

By the way, great job on this, thanks for open sourcing it! :+1:

**Comment by zjuasmn** [comment]
This file works fine on my browser(chrome 59).
<img width="1578" alt="qq20170727-202700 2x" src="https://user-images.githubusercontent.com/4462778/28670218-51b9959e-730a-11e7-980d-a56d4908f945.png">
 Which browser are you using? It is an error with file uploading.

**Comment by pedroms** [comment]
Yeah, see from your commit that this has to do with cross domain access. Uploading the file works fine though. Thanks anyway!
